### ISSUE TITLE
Crash when using /clan home to teleport from other dimensions

### ISSUE THREAD

**Issue by zellfrey** [The-Fireplace-Minecraft-Mods/Clans#50]
When a player is in another dimension and uses `/clan home` to teleport to the overworld(or i guess wherever the clan is located) a server crash occurs. 
```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.Teleporter.func_180620_b(Teleporter.java:134)
	at com.therandomlabs.randompatches.common.RPTeleporter.func_180620_b(RPTeleporter.java:46)
	at net.minecraft.world.Teleporter.func_180266_a(Teleporter.java:34)
	at com.therandomlabs.randompatches.common.RPTeleporter.func_180266_a(RPTeleporter.java:37)
	at net.minecraft.world.Teleporter.placeEntity(Teleporter.java:436)
	at com.therandomlabs.randompatches.common.RPTeleporter.placeEntity(RPTeleporter.java:73)
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:721)
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:624)
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695)
	at net.minecraft.entity.Entity.func_184204_a(Entity.java:2543)
	at the_fireplace.clans.commands.teleportation.CommandHome.teleportHome(CommandHome.java:71)
	at the_fireplace.clans.event.Timer.onServerTick(Timer.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_473_Timer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

This seems to only occur when the player has left his/her clan for 5 minutes, or when the chunks have unloaded. The crash report mentions the mod "random labs" however i haven't found any mention of a problem like this on their side

Clans-1.12.2-1.2.4
GrandEconomy-1.12.2-1.0.1

Forge version :1.12.2-14.23.5.2781

**Comment by The-Fireplace** [comment]
Yeah, this crash probably isn't their fault.
